[package]
name = "av1studio"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
num_cpus = "1.16.0"
regex = "1.11.1"
rfd = "0.15.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
